server:
  http_listen: ":8088"

database:
  host: "localhost"
  port: 3307
  user: "root"
  password: "123456"
  dbname: "course"
  max_open_conns: 20
  max_idle_conns: 5

redis:
  addr: "localhost:6399"
  password: ""
  db: 0
  dial_time_out : 2000

nats:
  url: "nats://localhost:4332"  # NATS 服务器地址


logging:
  level: "info"
  file: "logs/app.log"

metrics:
  prometheus_port: 9090


# 配置学生每学期最多能选择的课程数
max_courses_per_student: 5  # 每个学生最多选择5门课程