server:
  http_listen: ":8088"

database:
  host: "localhost"
  port: 3307
  user: "root"
  password: "123456"
  dbname: "course"
  max_open_conns: 20
  max_idle_conns: 5

redis:
  addr: "localhost:6399"
  password: ""
  db: 0
  dial_time_out : 2000

nats:
  url: "nats://localhost:4222"  # NATS 服务器地址


logging:
  level: "info"
  file: "logs/app.log"

metrics:
  prometheus_port: 9090
